/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'primary-fixed-dim': '#ffb95f',
        'tertiary-fixed-dim': '#4edea3',
        'on-secondary-fixed': '#001f26',
        'on-primary-container': '#201b00',
        'secondary-fixed': '#acedff',
        'inverse-on-surface': '#2c3039',
        'surface-bright': '#353942',
        'surface-container-highest': '#31353e',
        'surface-container-lowest': '#0a0e16',
        'on-tertiary': '#003824',
        outline: '#a2aec0',
        'secondary-fixed-dim': '#4cd7f6',
        tertiary: '#56e5a9',
        'inverse-surface': '#dfe2ee',
        'on-primary-fixed-variant': '#653e00',
        'on-primary-fixed': '#2a1700',
        'tertiary-fixed': '#6ffbbe',
        'surface-dim': '#0f131c',
        'on-tertiary-container': '#004e34',
        'tertiary-container': '#30c88f',
        surface: '#0f131c',
        secondary: '#4cd7f6',
        'on-primary': '#201b00',
        'on-tertiary-fixed': '#002113',
        'on-secondary-container': '#00424e',
        'surface-container-high': '#262a33',
        error: '#ffb4ab',
        'secondary-container': '#03b5d3',
        'on-error-container': '#ffdad6',
        'surface-container-low': '#181c24',
        'on-tertiary-fixed-variant': '#005236',
        'on-secondary-fixed-variant': '#004e5c',
        'surface-tint': '#ffb95f',
        'surface-variant': '#31353e',
        primary: '#ffd21c',
        'on-surface-variant': '#b5bfce',
        'primary-container': '#ffd21c',
        'surface-container': '#1c2028',
        'inverse-primary': '#855300',
        'error-container': '#93000a',
        background: '#0f131c',
        'on-secondary': '#003640',
        'on-background': '#dfe2ee',
        'outline-variant': '#534434',
        'on-surface': '#dfe2ee',
        'on-error': '#690005',
        'primary-fixed': '#ffddb8',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-lg': '1.25rem',
        gutter: '1rem',
        'gutter-lg': '1.5rem',
        margin: '1rem',
        'margin-lg': '2rem',
        'space-xl': '2rem',
        'space-sm': '0.5rem',
        'space-md': '0.75rem',
      },
      fontFamily: {
        'body-lg': ['Inter', 'sans-serif'],
        'telemetry-md': ['JetBrains Mono', 'monospace'],
        'telemetry-xl-mobile': ['JetBrains Mono', 'monospace'],
        'display-lg': ['Inter', 'sans-serif'],
        'telemetry-xl': ['JetBrains Mono', 'monospace'],
        'label-sm': ['Inter', 'sans-serif'],
        'display-lg-mobile': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['15px', { lineHeight: '22px', letterSpacing: '0em', fontWeight: '500' }],
        'telemetry-md': ['18px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '600' }],
        'telemetry-xl-mobile': ['26px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'display-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'telemetry-xl': ['36px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-sm': ['10px', { lineHeight: '14px', letterSpacing: '0.1em', fontWeight: '700' }],
        'display-lg-mobile': ['30px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '800' }],
        'headline-md': ['20px', { lineHeight: '26px', letterSpacing: '0em', fontWeight: '700' }],
        'body-md': ['13px', { lineHeight: '18px', letterSpacing: '0.01em', fontWeight: '400' }],
        'headline-lg-mobile': ['22px', { lineHeight: '28px', letterSpacing: '0em', fontWeight: '700' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.08em', fontWeight: '700' }],
        'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}
